version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: "raw data exo 2 dbt 1, circle sportswear"
    tables:
      - name: product
        identifier: raw_gz_product
        description: product_id et prix achat
      - name: sales
        identifier: raw_gz_sales
        description: date_date, orders_id, pdt_id, revenue, quantity
      - name: ship
        identifier: raw_gz_ship
        description: orders_id, shipping_fee, shipping_fee_1, logCost, ship_cost

models: 
  - name: product
    columns:
      - name: products_id
        description: prim key test of table product
        tests:
          - unique
          - not_null
  - name: ship
    columns:
      - name: orders_id
        description: prim key test of table ship
        tests:
          - unique
          - not_null            
           - not_null
  - name: sales
    columns:
      - name: date_date
      - name: orders_id
      - name: products_id
      - name: revenue
      - name: quantity
    tests:
      - unique:
              column_name: "(orders_id || '-' || products_id)"